package jimagesorter;

import java.awt.Component;
import java.io.*;
import javax.swing.*;
import java.awt.event.*;
import java.awt.image.BufferedImage;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardCopyOption;
import java.util.*;
import java.util.prefs.Preferences;
import javax.imageio.ImageIO;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author jcur002
 */
public class ImageSorterGUI extends javax.swing.JFrame implements KeyListener{

    String strImageSourceDirectory;
    String strFiledImageDirectory;
    boolean bFileClassifiedImages;
    List<File> imageFiles;
    ListIterator<File> imageIterator;
    TreeMap<String, ImageResult> imageInfo;
    File currentImageFile;
    
    TreeMap<Integer, HotkeyDirectoryPair> mapKeyDirs;
    java.util.List<String> Hotkeys;
    
    JImagePanel imagePanel;

     /**
     * Creates new form ImageSorterGUI
     */
    public ImageSorterGUI() {
        initComponents();
        addImagePanel();
        
        
        addKeyListener(this);
        setFocusable(true);
        setFocusTraversalKeysEnabled(false);

        Preferences prefs = Preferences.userNodeForPackage(this.getClass());
        strImageSourceDirectory = prefs.get("IMAGE_SOURCE_DIR", null);

        if (strImageSourceDirectory == null || !(new File(strImageSourceDirectory)).exists()) {
            strImageSourceDirectory = System.getProperty("user.home");
            File f = new File(strImageSourceDirectory);
            strImageSourceDirectory = f.getAbsolutePath();
            prefs.put("IMAGE_SOURCE_DIR", strImageSourceDirectory);
        }
        
        String strFileImages = prefs.get("FILE_IMAGES", null);
        bFileClassifiedImages = (strFileImages != null) ? Boolean.parseBoolean(strFileImages) : false;

        loadHotkeys();

        jLabelImageSourceDirectory.setText(strImageSourceDirectory);

        imageFiles = getImageList();
        imageIterator = imageFiles.listIterator();
        String strLabel = "# Images: " + imageFiles.size();
        jLabelNumImages.setText(strLabel);
        
        getImageInfo();
        
        if(imageIterator.hasNext()){
            BufferedImage theImage = null;
            try{
                currentImageFile = imageIterator.next();
                this.setTitle(currentImageFile.getName());
                theImage = ImageIO.read(currentImageFile);
            }catch(IOException e){
                e.printStackTrace();
            }
            if(theImage != null){
                imagePanel.drawImage(theImage);
            }
            
            if(imageInfo != null){
                String strResultLabel = imageInfo.get(currentImageFile.getName()).format();
                jLabelImageInfo.setText(strResultLabel);               
            }
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonSetDirectory = new javax.swing.JButton();
        jLabelImageSourceDirectory = new javax.swing.JLabel();
        jLabelNumImages = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabelImageInfo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuConfigure = new javax.swing.JMenu();
        jMenuItemSetDirectories = new javax.swing.JMenuItem();
        jMenuItemSetClasses = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonSetDirectory.setText("Set Directory");
        jButtonSetDirectory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSetDirectoryActionPerformed(evt);
            }
        });

        jLabelImageSourceDirectory.setText("jLabel1");

        jLabelNumImages.setText("# Images:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 266, Short.MAX_VALUE)
        );

        jMenu1.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Quit");
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenuConfigure.setText("Configure");

        jMenuItemSetDirectories.setText("Set Image Directories...");
        jMenuItemSetDirectories.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSetDirectoriesActionPerformed(evt);
            }
        });
        jMenuConfigure.add(jMenuItemSetDirectories);

        jMenuItemSetClasses.setText("Set Image Classes...");
        jMenuItemSetClasses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSetClassesActionPerformed(evt);
            }
        });
        jMenuConfigure.add(jMenuItemSetClasses);

        jMenuBar1.add(jMenuConfigure);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelImageSourceDirectory, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelNumImages, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(15, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonSetDirectory)
                        .addGap(123, 123, 123)
                        .addComponent(jLabelImageInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSetDirectory)
                    .addComponent(jLabelImageInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelImageSourceDirectory, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNumImages)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addImagePanel(){
        imagePanel = new JImagePanel(null);
        javax.swing.GroupLayout imagePanelLayout = new javax.swing.GroupLayout(imagePanel);
        imagePanel.setLayout(imagePanelLayout);
        imagePanelLayout.setHorizontalGroup(imagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        imagePanelLayout.setVerticalGroup(imagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 288, Short.MAX_VALUE)
        );
        GroupLayout gl = (GroupLayout)getContentPane().getLayout();
        gl.replace(jPanel1, imagePanel);
        pack();
    }
    private void deleteImage() throws IOException{
        imageIterator.remove();
        updateFileCount();
        currentImageFile.delete();
        nextImage();
    }
    
    private void moveImage(char key) throws IOException{
        // determine if key is actually a Hotkey
        
        if(Hotkeys.contains(Character.toString(key))){
            String hotKey = Character.toString(key);
            int whichKey = Hotkeys.indexOf(hotKey);
            String strTarget = mapKeyDirs.get(whichKey + 1).getDirectory() + '\\' + currentImageFile.getName();
            
          
            if(!strTarget.equals(null)){
                Path src = currentImageFile.toPath();
                Path dest = (new File(strTarget)).toPath();
                Files.copy(src, dest, StandardCopyOption.REPLACE_EXISTING);
                System.out.println("Copied " + src.toString());
                System.out.println("From:  " + dest.toString());
                System.out.println("To:  " + strTarget);
                
                //dest = (new File(strImageSourceDirectory + "\\filed\\" + currentImageFile.getName())).toPath();
                dest = (new File("D:\\temp\\new\\filed\\" + currentImageFile.getName())).toPath();
                Files.move(src, dest, StandardCopyOption.REPLACE_EXISTING);
                System.out.println("Moved " + src.toString());
                System.out.println("From:  " + dest.toString());
                System.out.println("To:  " + strTarget);
                
                imageIterator.remove();
                updateFileCount();
                nextImage();
            }
        }
    }
    
    private void nextImage() throws IOException{
        if(imageIterator.hasNext()){
            BufferedImage theImage = null;
            try{
                currentImageFile = imageIterator.next();
                this.setTitle(currentImageFile.getName());
                theImage = ImageIO.read(currentImageFile);
            }catch(IOException e){
                e.printStackTrace();
            }
            if(theImage != null){
                imagePanel.drawImage(theImage);
            }
            
            if(imageInfo != null){
                String strResultLabel = imageInfo.get(currentImageFile.getName()).format();
                jLabelImageInfo.setText(strResultLabel);
            }
        }
    }
    
    private void previousImage() throws IOException{
        if(imageIterator.hasPrevious()){
            BufferedImage theImage = null;
            try{
                currentImageFile = imageIterator.previous();
                this.setTitle(currentImageFile.getName());
                theImage = ImageIO.read(currentImageFile);
            }catch(IOException e){
                e.printStackTrace();
            }
            if(theImage != null){
                imagePanel.drawImage(theImage);
            }
            
            if(imageInfo != null){
                String strResultLabel = imageInfo.get(currentImageFile.getName()).format();
                jLabelImageInfo.setText(strResultLabel);
            }
        }
    }
    
    private void getImageInfo(){
        File resultsFile = new File(strImageSourceDirectory + "/results.csv");
        
        if(resultsFile.exists() && !resultsFile.isDirectory()){
           try{
               List<String> lines = Files.readAllLines(resultsFile.toPath());
               ListIterator<String> i = lines.listIterator();
               
               imageInfo = new TreeMap<>();
               while(i.hasNext()){
                   ImageResult ir = new ImageResult(i.next());
                   imageInfo.put(ir.getName(), ir);
               }
           }catch(IOException e){
               e.printStackTrace();
           } 
        }else{
            imageInfo = null;
        }
    }
    
    private List<File> getImageList() {
        File dir = new File(strImageSourceDirectory);
        File[] files = dir.listFiles((File directory, String fileName) -> fileName.toLowerCase().endsWith(".jpg"));

        return new ArrayList<>(Arrays.asList(files));
    }

    private void loadHotkeys() {
        mapKeyDirs = new TreeMap<>();
        Hotkeys = new ArrayList<>();

        Preferences prefs = Preferences.userNodeForPackage(this.getClass());

        for (int i = 1; i <= 10; i++) {
            String suffix = ((i < 10) ? Integer.toString(i) : "0");
            String strHotkeyKey = "KEY" + suffix;
            String strDirKey = "DIR" + suffix;

            String strHotkeyValue = prefs.get(strHotkeyKey, suffix);
            String strDirValue = prefs.get(strDirKey, null);

            Hotkeys.add(strHotkeyValue);

            try {
                mapKeyDirs.put(i, new HotkeyDirectoryPair(strHotkeyValue, strDirValue));
            } catch (InvalidHotkeyException e) {
                System.out.println(e.getMessage());
            }
        }
    }

    private void updateFileCount(){
        String strLabel = "# Images: " + imageFiles.size();
        jLabelNumImages.setText(strLabel);
    }

    private void jButtonSetDirectoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSetDirectoryActionPerformed
        

    }//GEN-LAST:event_jButtonSetDirectoryActionPerformed

    private void jMenuItemSetDirectoriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSetDirectoriesActionPerformed
        JFileChooser chooser = new JFileChooser();

        chooser = new JFileChooser();
        chooser.setCurrentDirectory(new File(strImageSourceDirectory));
        chooser.setDialogTitle("Select the image directory");
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        //
        // disable the "All files" option.
        //
        chooser.setAcceptAllFileFilterUsed(false);
        //    
        if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            strImageSourceDirectory = chooser.getSelectedFile().getAbsolutePath();
            jLabelImageSourceDirectory.setText(strImageSourceDirectory);
            Preferences prefs = Preferences.userNodeForPackage(this.getClass());
            prefs.put("CURRENT_WORKING_DIR", strImageSourceDirectory);

            imageFiles = getImageList();
            imageIterator = imageFiles.listIterator();
            String strLabel = "# Images: " + imageFiles.size();
            jLabelNumImages.setText(strLabel);
            
            getImageInfo();

            if(imageIterator.hasNext()){
                BufferedImage theImage = null;
                try{
                    currentImageFile = imageIterator.next();
                    theImage = ImageIO.read(currentImageFile);
                }catch(IOException e){
                    e.printStackTrace();
                }
                if(theImage != null){
                    imagePanel.drawImage(theImage);
                }
                
                if(imageInfo != null){
                    String strResultLabel = imageInfo.get(currentImageFile.getName()).format();
                    jLabelImageInfo.setText(strResultLabel);
                }
            }

//            try {
//                refreshImageStack();
//            } catch (IOException e) {
//                JOptionPane.showMessageDialog(this,
//                        "IOException while loading images",
//                        "Exception",
//                        JOptionPane.ERROR_MESSAGE);
//            }

        }
        
                
        Component z = this.getFocusOwner();
        this.requestFocus();
        
        
    }//GEN-LAST:event_jMenuItemSetDirectoriesActionPerformed

    private void jMenuItemSetClassesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSetClassesActionPerformed
        SetClassesDlg dlg = new SetClassesDlg(this, true, mapKeyDirs, strImageSourceDirectory);
        dlg.pack();
        dlg.setVisible(true);

        if (dlg.result == SetClassesDlg.DialogResult.OK_OPTION) {
            Preferences prefs = Preferences.userNodeForPackage(this.getClass());
            mapKeyDirs.putAll(dlg.getData());

            for (int i = 1; i <= 10; i++) {
                String suffix = ((i < 10) ? Integer.toString(i) : "0");
                String strHotkeyKey = "KEY" + suffix;
                String strDirKey = "DIR" + suffix;

                prefs.put(strHotkeyKey, mapKeyDirs.get(i).getHotkey());
                prefs.put(strDirKey, mapKeyDirs.get(i).getDirectory());
            }
        }
    }//GEN-LAST:event_jMenuItemSetClassesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ImageSorterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ImageSorterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ImageSorterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ImageSorterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ImageSorterGUI().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSetDirectory;
    private javax.swing.JLabel jLabelImageInfo;
    private javax.swing.JLabel jLabelImageSourceDirectory;
    private javax.swing.JLabel jLabelNumImages;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuConfigure;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItemSetClasses;
    private javax.swing.JMenuItem jMenuItemSetDirectories;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void keyTyped(KeyEvent ke) {
     }

    @Override
    public void keyReleased(KeyEvent ke) {
    }

    @Override
    public void keyPressed(KeyEvent ke) {
        
        
        char c = ke.getKeyChar();
        int keyCode = ke.getKeyCode();
             
        switch(keyCode){
            case KeyEvent.VK_BACK_SPACE:
            case KeyEvent.VK_DELETE:
                try{
                    deleteImage();
                }catch(IOException e){
                    e.printStackTrace();
                }
                break;
            case KeyEvent.VK_LEFT:
            case KeyEvent.VK_UP:
                try{
                    previousImage();
                }catch(IOException e){
                    e.printStackTrace();
                }
                break;
            case KeyEvent.VK_RIGHT:
            case KeyEvent.VK_DOWN:
                try{
                    nextImage();
                }catch(IOException e){
                    e.printStackTrace();
                }
                break;
            case KeyEvent.VK_Z:
                if(ke.isControlDown())
                    System.out.println("Ctrl-Z typed");
                break;
            default:
               try{
                   moveImage(c);
               }catch(IOException e){
                    e.printStackTrace();
               } 
        }
    }
}
